# Social Media Links
- platform: x
  label: X (Twitter)
  url: https://x.com/FreshJuiceDev

- platform: github
  label: GitHub
  url: https://github.com/fermionicplants

- platform: linkedin
  label: LinkedIn
  url: https://www.linkedin.com/company/freshjuice
