# Social Media Links
- platform: x
  label: X (Twitter)
  url: https://github.com/fermionicplants

- platform: github
  label: GitHub
  url: https://github.com/fermionicplants

- platform: linkedin
  label: LinkedIn
  url: https://github.com/fermionicplants
